#%RAML 1.0
title: Pet shop
version: 1
baseUri: /shop

types:
  Pet:
    properties:
      name: string
      kind: string
      price: number

/pets:
  get:
    responses:
      200:
        body:
          application/json:
  post:
    body:
      application/json:
        type: Pet
        example: |
          {
            "name": "Snoopy",
            "kind": "Mammal",
            "price": 100
          }
  /{id}:
    put:
      body:
        application/json:
    delete:
      responses:
        204:
