#%RAML 1.0
title: Pet shop
uses:
  PetLibrary: PetLibrary.raml
version: 1
baseUri: /shop

types:
  Mammal:
    type: PetLibrary.Pet
  Bird:
    type: PetLibrary.Pet
    properties:
      wingLength: number

/pets:
  type:  { PetLibrary.Collection: {item : PetLibrary.Pet } }
  get:
    is:
      - PetLibrary.FilterableByPrice
    queryParameters:
      petKind:
        enum: [bird, mammal]
  /{id}:
    type:  { PetLibrary.Member: {item : PetLibrary.Pet } }

/birds:
  type: { PetLibrary.Collection: {item: Bird} }
  get:
    is:
      - PetLibrary.FilterableByPrice
  /{id}:
    type: { PetLibrary.Member: {item : Bird} }

/mammals:
  type: { PetLibrary.Collection: {item: Mammal} }
  get:
    is:
      - PetLibrary.FilterableByPrice
  /{id}:
    type: { PetLibrary.Member: {item : Mammal} }
